package com.gm.circley.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gm.circley.db.DBPhoto;

import com.gm.circley.db.dao.DBPhotoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBPhotoDaoConfig;

    private final DBPhotoDao dBPhotoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBPhotoDaoConfig = daoConfigMap.get(DBPhotoDao.class).clone();
        dBPhotoDaoConfig.initIdentityScope(type);

        dBPhotoDao = new DBPhotoDao(dBPhotoDaoConfig, this);

        registerDao(DBPhoto.class, dBPhotoDao);
    }
    
    public void clear() {
        dBPhotoDaoConfig.clearIdentityScope();
    }

    public DBPhotoDao getDBPhotoDao() {
        return dBPhotoDao;
    }

}
